###회원가입
POST /api/accounts
Host: localhost:8080
Content-Type: application/json

{
  "loginId": "",
  "password": "",
  "name": "",
  "email": ""
}

###수정
PUT /api/accounts/{id}
Host: localhost:8080
Content-Type: application/json

{
  "loginId": "",
  "password": "",
  "name": "",
  "email": ""
}

###회원탈퇴
POST /api.accounts/{id}
Host: localhost:8080
Content-Type: application/json