### 계정 생성 요청
POST /api/accounts
Host: localhost:7070
Content-Type: application/json

{
  "loginId": "test2",
  "password": "pw2222222",
  "email": "TT2@gmail.com",
  "name": "TT2"
}

### 로그인
GET /api/login?loginId=test
HOST: localhost:7070
Content-Type: application/json

{
  "loginId": "test2",
  "password": "pw2222222"
}


### 로그인후 요청
GET /api/auth/test
HOST: localhost:7070
Content-Type: application/json


### 계정 조회
GET /api/accounts/1
Host: localhost:7070
Content-Type: application/json


### 계정 수정 요청
PUT /api/accounts/8
Host: localhost:7070
Content-Type: application/json

{
  "loginId": "testUpdate",
  "password": "pw2123433333",
  "email": "TT2@gmail.com",
  "name": "TT2",
  "status": "휴면"
}


### 계정 삭제 요청
DELETE /api/accounts/7
Host: localhost:7070


### 모든 계정 조회
GET /api/accounts/group
Host: localhost:7070
