### 아이디 비밀번호 요청
GET /api/accounts/{id}
Host: localhost:7070
Content-Type: application/json


### 계정 생성 요청
POST /api/accounts
Host: localhost:7070
Content-Type: application/json

{
  "loginId": "test2",
  "password": "pw2222222",
  "email": "TT2@gmail.com",
  "name": "TT2"
}

### 수정할 계정 조회
GET /api/accounts/modify/6
Host: localhost:7070
Accept: application/json

### 계정 수정 요청
PUT /api/accounts/modify/6
Host: localhost:7070
Content-Type: application/json

{
  "loginId": "testUpdate",
  "password": "pw2123433333",
  "email": "TT2@gmail.com",
  "name": "TT2",
  "status": "휴면"
}


### 계정 삭제 요청
DELETE /api/accounts/{id}
Host: localhost:7070


### 계정 조회



