
### 계정 생성 요청
POST /api/accounts
Host: localhost:7070
Content-Type: application/json

{
  "loginId": "test2",
  "password": "pw2",
  "email": "TT2@gmail.com",
  "name": "TT2",
  "authority": "관리자"
}

### 계정 생성 응답
HTTP/1.1 201 Created
Content-Type: application/json

{
  "id": "",
  "loginId": "",
  "password": "",
  "name": "",
  "email": "",
  "memberStatus":{
    "id": 1,
    "status": ""
  },
  "authority":  {
    "id": 1,
    "authority": ""
  }
}

### 계정 수정 요청
PUT /api/accounts/6
Host: localhost:7070
Content-Type: application/json

{
  "loginId": "test2",
  "password": "pw2",
  "email": "TT2@gmail.com",
  "name": "TT2",
  "memberStatus": "휴면"
}

### 계정 수정 응답

HTTP/1.1 200 OK
Content-Type: application/json

{
  "id": "",
  "loginId": "",
  "name": "",
  "email": ""
}

### 계정 삭제 요청
DELETE /api/accounts/{id}

### 계정 삭제 응답


